fix(datadog): Non-map values for error key (#166)
Passing an `error` key is a really easy footgun:

```elixir
Logger.error("Something bad happened", error: "{:error, :something_bad}")
```

Currently, the formatter crashes because it expects `error` to be a map.
This PR fixes the issue by assuming the caller was not trying to define
the error map, and instead nests the value _inside_ the error map:

```elixir
%{
  error: %{
    kind: "error",
    message: "Something bad happened",
    error: "{:error, :something_bad}"
  }
}
```